image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  GIT_DEPTH: 0
  CN_IMAGE: central-back
  HN_IMAGE: community-back

stages:
  - build-central-back
  - build-hub-back

# Build central back
build-central-back:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  stage: build-central-back
  script:
    # retrieve version number from tag ex : cn_1.0.0
    - export VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f2)
    # Build the docker image from Dockerfile with the latest tag and a tag for the version
    - docker build --tag $CI_REGISTRY_IMAGE/$CN_IMAGE:$VERSION --tag $CI_REGISTRY_IMAGE/$CN_IMAGE:latest -f apps/cn-central-back/Dockerfile .
    # Push both image in the registry
    - docker push $CI_REGISTRY_IMAGE/$CN_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE/$CN_IMAGE:latest
  only:
    - /cn_.*/

# Build hub back
build-hub-back:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  stage: build-hub-back
  script:
    # retrieve version number from tag ex : hn_1.0.0
    - export VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f2)
    # Build the docker image from Dockerfile with the latest tag and a tag for the version
    - docker build --tag $CI_REGISTRY_IMAGE/$HN_IMAGE:$VERSION --tag $CI_REGISTRY_IMAGE/$HN_IMAGE:latest -f apps/hn-hub/Dockerfile .
    # Push both image in the registry
    - docker push $CI_REGISTRY_IMAGE/$HN_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE/$HN_IMAGE:latest
  only:
    - /hn_.*/
