image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  GIT_DEPTH: 0
  LAB_FRONT_IMAGE: lab-front
  CA_IMAGE: central-front

stages:
  - build-lab
  - build-central

# Build lab front
build-lab:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  stage: build-lab
  script:
    # retrieve version number from tag ex : ca_1.0.0
    - export VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f2)
    # Build the docker image from Dockerfile with the latest tag and a tag for the version
    - docker build --tag $CI_REGISTRY_IMAGE/$LAB_FRONT_IMAGE:$VERSION --tag $CI_REGISTRY_IMAGE/$LAB_FRONT_IMAGE:latest -f apps/lab-front/Dockerfile .
    # Push both image in the registry
    - docker push $CI_REGISTRY_IMAGE/$LAB_FRONT_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE/$LAB_FRONT_IMAGE:latest
  only:
    - /lab_.*/

# Build central front
build-central:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  stage: build-central
  script:
    # retrieve version number from tag ex : ca_1.0.0
    - export VERSION=$(echo $CI_COMMIT_TAG | cut -d'_' -f2)
    # Build the docker image from Dockerfile with the latest tag and a tag for the version
    - docker build --tag $CI_REGISTRY_IMAGE/$CA_IMAGE:$VERSION --tag $CI_REGISTRY_IMAGE/$CA_IMAGE:latest -f apps/ca-central-front/Dockerfile .
    # Push both image in the registry
    - docker push $CI_REGISTRY_IMAGE/CA_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE/CA_IMAGE:latest
  only:
    - /ca_.*/



