image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  GIT_DEPTH: 0
  LAB_FRONT_IMAGE: lab-front


stages:
  - build-lab
  - deploy-lab

# Build lab front an create an artifact with dist folder
build-lab:
  image: node:14-alpine
  stage: build-lab
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker  manifest inspect registry.gitlab.com/gencovery/core/monorepo/lab-front:11ac0a0042acc90452feb2207a92145cd190cb40 > /dev/null && exit || true
    - npm ci
    - npm run lab-front:build-prod
  artifacts:
    expire_in: 1 day
    paths:
      - dist/apps/lab-front/
  only:
    - ben

# Push lab-front image to the docker registry using Dockerfile of the lab-front
deploy-lab:
  image: node:14-alpine
  stage: deploy-lab
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - export VERSION=$(node -p "require('./apps/lab-front/version.json').version")
    # Build the docker image from Dockerfile with a latest tag and a tag for the commit
    - docker build --cache-from $CI_REGISTRY_IMAGE/$LAB_FRONT_IMAGE:latest --tag $CI_REGISTRY_IMAGE/$LAB_FRONT_IMAGE:$VERSION --tag $CI_REGISTRY_IMAGE/$LAB_FRONT_IMAGE:latest . -f apps/lab-front/Dockerfile
    # Push both image in the registry
    - docker push $CI_REGISTRY_IMAGE/$LAB_FRONT_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE/$LAB_FRONT_IMAGE:latest
  only:
    - ben


