import {
  Component,
  ElementRef,
  HostBinding,
  Input,
  OnDestroy,
  OnInit,
  SecurityContext,
  TemplateRef,
  ViewChild,
  ViewContainerRef
} from '@angular/core';
import {DomSanitizer} from '@angular/platform-browser';
import {FlPortalService} from '../../../fl-portal/service/fl-portal.service';
import {FlOverlayRef} from '../../../fl-portal/model/fl-overlay-ref.class';
import {FlTextEditorState} from '../../fl-text-editor.state';
import {FlResizeEvent} from '../../../fl-core-directive/fl-resize/fl-resize.directive';

/**
 * Figure component in text editor generated by {@link FlTextEditorFigureBlot}
 */
@Component({
  selector: 'fl-text-editor-figure',
  templateUrl: './fl-text-editor-figure.component.html',
  styleUrls: ['./fl-text-editor-figure.component.scss']
})
export class FlTextEditorFigureComponent implements OnInit, OnDestroy {

  @HostBinding('attr.src')
  @Input() src: string;

  @HostBinding('attr.width')
  @Input() width: string;

  @HostBinding('attr.height')
  @Input() height: string;

  @HostBinding('attr.image-title')
  @Input() imageTitle: string;

  @HostBinding('attr.caption')
  @Input() caption: string;

  @ViewChild('figure') figure: ElementRef<HTMLElement>;

  @ViewChild('templatePortalContent') templatePortalContent: TemplateRef<unknown>;

  sanitizedUrl: string;

  private overlayRef: FlOverlayRef;

  constructor(private sanitizer: DomSanitizer,
              private portalService: FlPortalService,
              private viewContainerRef: ViewContainerRef,
              private elementRef: ElementRef<HTMLElement>) {
  }

  ngOnInit(): void {
    this.sanitizedUrl = this.sanitizer.sanitize(SecurityContext.URL, this.src);
  }

  openPortal(): void {
    if (FlTextEditorState.isDisable(this.elementRef.nativeElement)) return;
    if (this.overlayRef) return;

    const config = this.portalService.configureRelativePortal(this.figure.nativeElement,
      ['bottom', 'top'], {disposeOnOutsideClick: true});

    this.overlayRef = this.portalService.createPortalTemplate(this.templatePortalContent, config, this.viewContainerRef);
    this.overlayRef.detachments().subscribe(() => this.overlayRef = null);
  }

  closeOverlay(): void {
    this.overlayRef?.dispose();
  }

  onImageResize(resizeEvent: FlResizeEvent): void {
    this.width = resizeEvent.width + '';
    this.height = resizeEvent.height + '';
  }

  ngOnDestroy(): void {
    this.closeOverlay();
  }


}
