import {
  Component,
  ElementRef,
  HostBinding,
  Input,
  OnDestroy,
  OnInit,
  SecurityContext,
  TemplateRef,
  ViewChild,
  ViewContainerRef
} from '@angular/core';
import {DomSanitizer} from '@angular/platform-browser';
import {FlTextEditorState} from '../../state/fl-text-editor.state';
import {FlResizeEvent} from '../../../fl-resize/fl-resize/fl-resize.directive';
import {FlTextEditorsManagerState} from '../../state/fl-text-editors-manager.state';
import {Observable} from 'rxjs';
import {FlTextEditorImageLoader} from '../../model/fl-text-editor-image.class';
import {FlDialogService} from '../../../fl-dialog/fl-dialog.service';
import {MatDialogRef} from '@angular/material/dialog';

/**
 * Figure component in text editor generated by {@link FlTextEditorFigureBlot}
 */
@Component({
  selector: 'fl-text-editor-figure',
  templateUrl: './fl-text-editor-figure.component.html',
  styleUrls: ['./fl-text-editor-figure.component.scss']
})
export class FlTextEditorFigureComponent implements OnInit, OnDestroy {

  @HostBinding('attr.filename')
  @Input() filename: string;

  @Input() naturalWidth: string;

  @Input() naturalHeight: string;

  @HostBinding('attr.width')
  @Input() width: string;

  @HostBinding('attr.height')
  @Input() height: string;

  @HostBinding('attr.image-title')
  @Input() imageTitle: string;

  @HostBinding('attr.caption')
  @Input() caption: string;

  @ViewChild('figure') figure: ElementRef<HTMLElement>;

  @ViewChild('templatePortalContent') templatePortalContent: TemplateRef<unknown>;

  imageWidth: number;
  imageHeight: number;

  sanitizedUrl: string;

  private dialogRef: MatDialogRef<any>;

  private state: FlTextEditorState;
  private config: FlTextEditorImageLoader;

  disabled$: Observable<boolean>;

  constructor(private sanitizer: DomSanitizer,
              private dialogService: FlDialogService,
              private viewContainerRef: ViewContainerRef,
              private elementRef: ElementRef<HTMLElement>,
              private managersState: FlTextEditorsManagerState) {
    this.state = managersState.getState(elementRef.nativeElement);
    this.config = this.state.config as any;
  }

  ngOnInit(): void {
    this.sanitizedUrl = this.sanitizer.sanitize(SecurityContext.URL, this.config.getImageUrl(this.filename));
    this.disabled$ = this.state.getDisabled$();
    this.initSize();
  }

  private initSize(): void {

    const width = parseFloat(this.width);
    const height = parseFloat(this.height);
    // if the size of the image was not modified
    if (this.width === this.naturalWidth && this.height === this.naturalHeight) {
      const parentWidth = this.elementRef.nativeElement.clientWidth;

      // if the image is larger than container, resize it
      if (parentWidth > 0 && width > parentWidth) {
        this.imageWidth = parentWidth;
        this.imageHeight = ((parentWidth / width) * parseFloat(this.height));
      }
    } else {
      this.imageWidth = width;
      this.imageHeight = height;
    }
  }


  openEditDialog(): void {
    this.dialogRef = this.dialogService.openSmallDialog(this.templatePortalContent);
  }

  closeOverlay(): void {
    this.dialogRef?.close();
  }

  onImageResize(resizeEvent: FlResizeEvent): void {
    this.width = resizeEvent.width + '';
    this.height = resizeEvent.height + '';
  }

  ngOnDestroy(): void {
    this.closeOverlay();
  }


}
