server {
      listen 81;
      server_name gencovery.com;

      # Point to index.html
      root   /usr/share/nginx/html;
      index  index.html index.htm;

      # Security header configuration
      add_header Cache-Control no-cache;
      # add_header X-Frame-Options "DENY";
      add_header X-Content-Type-Options nosniff;
      add_header X-Xss-Protection "1; mode=block" always;

      # CSP FOR LOCAL ENV contains localhost:3001 in src
      # DO NOT COMMIT THIS LINE UNCOMMENTED
      # add_header Content-Security-Policy "default-src 'self' 'unsafe-eval' localhost:3001; script-src-elem 'self' localhost:3001 data:; frame-src 'self' *.gencovery.com *.gencovery.io; worker-src  data: 'self' blob:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: http: https: *.gencovery.com; font-src 'self' data: http: https: fonts.googleapis.com; connect-src 'self' https://fonts.googleapis.com localhost:3000;";

      # CSP FOR PROD ENV
      # script-src-element 'data:' --> allow loading script from base 64 with 'data:' for json editor
      # child-src --> equivalent of worker-src for safari
      add_header Content-Security-Policy "default-src 'self' *.gencovery.com *.gencovery.io; script-src-elem 'self' *.gencovery.com *.gencovery.io data:; frame-src 'self' *.gencovery.com *.gencovery.io; worker-src *.gencovery.com *.gencovery.io data: 'self' blob:; child-src *.gencovery.com *.gencovery.io data: 'self' blob:; style-src 'self' 'unsafe-inline' *.gencovery.com *.gencovery.io https://fonts.googleapis.com; img-src 'self' blob: data: http: https: *.gencovery.com *.gencovery.io; font-src 'self' data: http: https: fonts.googleapis.com; connect-src 'self' *.gencovery.com *.gencovery.io https://fonts.googleapis.com https://fonts.gstatic.com";

      add_header Referrer-Policy "no-referrer-when-downgrade";
      add_header Feature-Policy "accelerometer 'none'; autoplay 'none'; camera 'none' encrypted-media 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; speaker 'none'; vr 'none'; vibrate 'none'";

      location / {
          try_files $uri $uri/ /index.html;
      }
}
