import {ClStringHelper} from '@monorepo/core-lib';

export type FlChartLabelFormatFunction = (domainValue: number, index: number) => string;

export class FlChartLabelFormatter {

  /**
   * Format the label base on the format function
   * @param shortFormat the format function for the short label
   * @param shortFormatMaxLength the max length of the label generated by the short format function
   * (use to anticipate the space needed)
   * @param longFormat the format function for the long label
   */
  constructor(private shortFormat: FlChartLabelFormatFunction, public shortFormatMaxLength: number,
              private longFormat: FlChartLabelFormatFunction = shortFormat) {
  }

  /**
   * Create the format function for the axis from a list of label
   * It considers the value as index and pick the label at this index
   * @param tickLabels
   */
  public static fromTickLabels(tickLabels: string[]): FlChartLabelFormatter {
    return new FlChartLabelFormatter(
      (value) => tickLabels[value] ?? value.toString(),
      tickLabels.reduce((p, c) => Math.max(p, c?.toString()?.length ?? 0), 0)
    );
  }

  /**
   * Format the lab base on the format function
   * @param domainValue
   * @param index the index of the domain value, can be null
   * @param maxLength truncate the label to this length
   */
  public formatShort(domainValue: number, index: number = null, maxLength: number = null): string {
    const label = this.shortFormat(domainValue, index);
    if (maxLength) {
      return ClStringHelper.limiteLength(label, maxLength);
    }
    return label;
  }

  public formatLong(domainValue: number): string {
    return this.longFormat(domainValue, null);
  }

}
