export interface SnDocument {
  id: string;
  title: string;
  source: 'pubmed';
  authors: string[];
  date: string;
  doi: string;
  urlPath: string;
  content: string;
  sentences: SnDocumentSentence[];
}

export type SnEffect = 'Positive' | 'Negative' | 'Neutral';

export interface SnDocumentSentence {
  parts: SnDocumentSentencePart[];
  context: string[];
  sentence: string;
}

export interface SnDocumentSentencePart {
  subject: string[];
  verb: string;
  object: string;
  type: SnEffect;
  humanValidated: boolean;
}


export interface SnDocSearchResult extends SnDocument {
  contentHighlight: string[];
  titleHighlights: SnMatchPosition[];
  sentences: SnDocSentenceSearchResult[];
}

export interface SnDocSentenceSearchResult extends SnDocumentSentence {
  sentenceHighlights: SnMatchPosition[];
}

export interface SnMatchPosition {
  offset: number;
  length: number;
}

/**
 * Format of the data generated by the Python script to import data in SmartDb
 */
export interface SnSmartDbScriptResult {
  data: SnSmartDbScriptDoc[];
}

/**
 * Format of one line in the smart db script
 */
export interface SnSmartDbScriptDoc {
  subject: string[];
  verb: string;
  object: string[];
  context: string[];
  type: string[];
  original_sentence: string;
  source: 'pubmed';
  title: string;
  text: string;
  authors: string;
  date: string;
  doi: string;
  url_path: string;
}

/**
 * Object to represent the export of the SMARTDB database
 * also used to create database
 */
export interface SnSmartDbExport {
  version: number;
  documents: SnDocument[];
}

export type SnFileImportContent =
  { type: 'export', fileContent: SnSmartDbExport } |
  { type: 'script', fileContent: SnSmartDbScriptResult }
