export class FlColorHelper {

  /**
   * return hexa color base generated by string with #
   */
  public static stringToRGBColor(str: string): string {
    return '#' + FlColorHelper.stringToRGB(str);
  }

  /**
   * return hexa color base generated by string
   */
  public static stringToRGB(str: string): string {
    return FlColorHelper.intToRGB(FlColorHelper.hashCode(str));
  }

  /**
   * return hexa color base generated by int
   */
  public static intToRGB(i: number): string {
    const c = (i & 0x00FFFFFF)
      .toString(16)
      .toUpperCase();

    return '00000'.substring(0, 6 - c.length) + c;
  }

  // get hash form string
  private static hashCode(str: string): number {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      hash = str.charCodeAt(i) + ((hash << 5) - hash);
    }
    return hash;
  }

  // return a list of colors
  public getColorList(): string[] {
    return ['#e41a1c', '#377eb8', '#4daf4a', '#984ea3',
      '#ff7f00', '#ffff33', '#a65628', '#f781bf', '#999999'];
  }
}
