export class FlColorHelper {

  public static blue: string = 'rgba(0,114,178,1)';
  public static red: string = 'rgba(213,92,0,1)';
  public static pinkShiny: string = '#ff0087';

  public static transparentBlue: string = 'rgba(0,114,178,0.8)';
  public static transparentRed: string = 'rgba(213,92,0,0.8)';


  /**
   * return hexa color base generated by string with #
   */
  public static stringToRGBColor(str: string): string {
    return '#' + FlColorHelper.stringToRGB(str);
  }

  /**
   * return hexa color base generated by string
   */
  public static stringToRGB(str: string): string {
    return FlColorHelper.intToRGB(FlColorHelper.hashCode(str));
  }

  /**
   * return hexa color base generated by int
   */
  public static intToRGB(i: number): string {
    const c = (i & 0x00FFFFFF)
      .toString(16)
      .toUpperCase();

    return '00000'.substring(0, 6 - c.length) + c;
  }

  // get hash form string
  private static hashCode(str: string): number {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      hash = str.charCodeAt(i) + ((hash << 5) - hash);
    }
    return hash;
  }

  // return a list of colors
  public static getColorList(): string[] {
    // return ['#e41a1c', '#377eb8', '#4daf4a', '#984ea3',
    //   '#ff7f00', '#ffff33', '#a65628', '#f781bf', '#999999'];
    // color for color blind : https://jfly.uni-koeln.de/color/
    return ['rgba(230,159,0,1)', 'rgba(86,180,233,1)', 'rgba(0,158,115,1)', 'rgba(240,228,66,1)',
      FlColorHelper.blue, FlColorHelper.red, 'rgba(204,121,167,1)'];

    // return ['#004949', '#ff6db6', '#490092', '#006ddb',
    //   '#920000', '#924900', '#24ff24', '#ffff6d',
    //   '#009292', '#ffb6db', '#b6dbff',  '#db6d00',
    //   '#b66dff', '#6db6ff'];
  }

  // return a list of colors that are slightly transparent
  public static getColorTransparentList(): string[] {
    // color for color blind : https://jfly.uni-koeln.de/color/
    return ['rgba(230,159,0,0.8)', 'rgba(86,180,233,0.8)', 'rgba(0,158,115,0.8)', 'rgba(240,228,66,0.8)',
      FlColorHelper.transparentBlue, FlColorHelper.transparentRed, 'rgba(204,121,167,0.8)'];
  }

  public static getColorFromIndex(index: number): string {
    const colors = FlColorHelper.getColorList();

    return colors[index % colors.length];
  }

  public static getColorsGroups(): string[][] {
    // return [
    //   ['#ffcdd2', '#ef9a9a', '#e57373'],
    //   ['#bbdefb', '#90caf9', '#64b5f6'],
    //   ['#f0f4c3', '#e6ee9c', '#dce775'],
    // ]
    return [
      ['#4a148c', '#6a1b9a', '#7b1fa2'],
      ['#303f9f', '#283593', '#1a237e'],
      ['#00796b', '#00695c', '#004d40'],
    ];
  }


}
