/**
 * List of error texts for translation
 */
export enum CnErrorText {
  SERVER_ERROR = 'error.server_error',
  WRONG_CREDENTIALS = 'error.wrong_credentials',
  USER_LOCKED = 'error.user_locked',
  COLUMN_TOO_LONG = 'error.column_too_long',
  EMAIL_ALREADY_EXIST = 'error.email_already_exist',
  ACCOUNT_NOT_ACTIVATED = 'error.account_not_activated',
  INVALID_LINK = 'error.invalid_link',
  ACCOUNT_ALREADY_ACTIVATED = 'error.account_already_activated',
  LINK_EXPIRED = 'error.link_expired',
  STATUS_NOT_CHANGED = 'error.status_not_changed',
  MISSING_API_KEY = 'error.missing_api_key',
  WRONG_API_KEY = 'error.wrong_api_key',
  WRONG_TOKEN = 'error.wrong_token',
  LAB_STOPPED = 'error.lab_stopped',
  LAB_AUTH_ERROR = 'error.lab_auth_error',
  ACCOUNT_NOT_ADMIN_ACTIVATED = 'error.account_not_admin_activated',
  LANGUAGE_NOT_SUPPORTED = 'error.language_not_supported',
  USER_ALREADY_EXIST_IN_LAB = 'error.user_already_exist_in_lab',
  LAB_USER_NOT_ACTIVATED = 'error.lab_user_not_activated',
  LAB_USER_NOT_FOUND = 'error.lab_user_not_found',
  PROJECT_ALREADY_SHARED_WITH_GROUP = 'error.project_already_shared_with_group',
  PROJECT_NOT_SHARED_WITH_GROUP = 'error.project_not_shared_with_group',
  USER_ALREADY_IN_GROUP = 'error.user_already_in_group',
  USER_NOT_IN_GROUP = 'error.user_not_in_group',
  USER_ALREADY_IN_ORGANIZATION = 'error.user_already_in_organization',
  USER_NOT_IN_ORGANIZATION = 'error.user_not_in_organization',
  REMOVE_GROUP_LAST_USER = 'error.remove_group_last_user',
  PROJECT_MUST_HAVE_A_GROUP ='error.project_must_have_a_group',
  EXP_MUST_BE_ASSOCIATED_WITH_LEAF_PROJECT = 'error.exp_must_be_associated_with_leaf_project',
  REPORT_MUST_BE_ASSOCIATED_WITH_LEAF_PROJECT = 'error.report_must_be_associated_with_leaf_project',
  CANNOT_DEACTIVATE_LAST_ADMIN = 'error.cannot_deactivate_last_admin',
  CANNOT_REMOVE_LAST_ADMIN = 'error.cannot_remove_last_admin',
  MAIL_NOT_SENT = 'error.mail_not_sent',
  ORGANIZATION_INVITATION_ALREADY_EXISTS = 'error.organization_invitation_already_exists',
  ORGANIZATION_INVITATION_EXPIRED = 'error.organization_invitation_expired',
  ORGANIZATION_INVITATION_INVALID = 'error.organization_invitation_invalid',
}
