name: Main Workflow space back

on:
  push:
    tags:
      - 'cn_*'

jobs:
  build_and_push_image:
    uses: ./.github/workflows/build_github_package.yml
    with:
      registry: ghcr.io
      image_name: ghcr.io/constellab/space-api
      tag_prefix: cn_
      dockerfile_path: ./apps/cn-space-api/Dockerfile
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}
